/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tampilan;

import static groovy.sql.Sql.resultSet;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Ozmond
 */
public class DataPenjualan extends javax.swing.JInternalFrame {
    private DefaultTableModel data;
    private String filename;
    String path2 = null;
    Connection conn;
    Statement stm;
    ResultSet rs;
    /**
     * Creates new form DataPelanggan
     */
    public DataPenjualan() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI BUI = (BasicInternalFrameUI) this.getUI();
        BUI.setNorthPane(null);
        kosong();
        tabel_penjualan();
        Tampil_ID();
    }
    
    private void kosong(){
        try {
            ResultSet rs = stm.executeQuery("SELECT * FROM data_penjualan ORDER BY id_transaksi DESC");

            if (rs.next()) {
                int lastID = Integer.parseInt(rs.getString("id_transaksi").substring(5));
                int newID = lastID + 1;
                String AN = String.format("%05d", newID);
                id_transaksi.setText("PNJLN" + AN);
            } else {
                id_transaksi.setText("PNJLN00001");
            }
        } catch (Exception e) {
            id_transaksi.setText("PNJLN00001");
        }
        tgl_transaksi.setDate(new Date());
        id_pelanggan.setText("");
        nama_pelanggan.setText("");
        alamat.setText("");
        no_telp.setText("");
        id_barang.setText("");
        jenis_baju.setText("");
        warna.setText("");
        biaya_persatuan.setText("");
        jumlah_pesanan.setText("");
        total_biaya.setText("");
        rbLunas.setSelected(false);
        rb20.setSelected(false);
        rb50.setSelected(false);
        total_bayar.setText("");
        foto_desain.setIcon(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        cariData = new javax.swing.JTextField();
        btnCariPenjualan = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_penjualan = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        id_transaksi = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        tgl_transaksi = new com.toedter.calendar.JDateChooser();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nama_pelanggan = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        id_pelanggan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        no_telp = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnCariPelanggan = new javax.swing.JButton();
        btnUploadImage = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        foto_desain = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        warna = new javax.swing.JTextField();
        total_biaya = new javax.swing.JTextField();
        jenis_baju = new javax.swing.JTextField();
        btnCariBarang = new javax.swing.JButton();
        biaya_persatuan = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jumlah_pesanan = new javax.swing.JTextField();
        btnHitung = new javax.swing.JButton();
        btnInput = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        rbLunas = new javax.swing.JRadioButton();
        rb20 = new javax.swing.JRadioButton();
        rb50 = new javax.swing.JRadioButton();
        jLabel24 = new javax.swing.JLabel();
        total_bayar = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        id_barang = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(236, 50, 55));
        jLabel19.setText("Tabel Data Penjualan");

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel20.setText("Cari Data");

        cariData.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        btnCariPenjualan.setBackground(new java.awt.Color(255, 255, 255));
        btnCariPenjualan.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btnCariPenjualan.setForeground(new java.awt.Color(236, 50, 55));
        btnCariPenjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-search-30 (1).png"))); // NOI18N
        btnCariPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariPenjualanActionPerformed(evt);
            }
        });

        tabel_penjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_penjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_penjualanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel_penjualan);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel19))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cariData)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCariPenjualan)
                .addGap(17, 17, 17))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCariPenjualan)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(cariData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(236, 60, 66));
        jLabel2.setText("Data Penjualan");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(574, 574, 574)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel8.setText("Id Transaksi");

        id_transaksi.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        id_transaksi.setEnabled(false);
        id_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_transaksiActionPerformed(evt);
            }
        });

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel21.setText("Tgl Transaksi");

        tgl_transaksi.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tgl_transaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                    .addComponent(id_transaksi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(id_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(tgl_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(236, 50, 55));
        jLabel9.setText("Data Pelanggan");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setText("Id Pelanggan");

        nama_pelanggan.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel10.setText("Nama Pelanggan");

        id_pelanggan.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        alamat.setColumns(20);
        alamat.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        alamat.setRows(5);
        jScrollPane1.setViewportView(alamat);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel11.setText("Alamat");

        no_telp.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel12.setText("No. Telp");

        btnCariPelanggan.setBackground(new java.awt.Color(255, 255, 255));
        btnCariPelanggan.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btnCariPelanggan.setForeground(new java.awt.Color(236, 50, 55));
        btnCariPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-search-30 (1).png"))); // NOI18N
        btnCariPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariPelangganActionPerformed(evt);
            }
        });

        btnUploadImage.setText("UP");
        btnUploadImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadImageActionPerformed(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel16.setText("Foto Desain");

        foto_desain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel16))
                                .addGap(47, 47, 47))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(foto_desain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nama_pelanggan, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                            .addComponent(no_telp)
                            .addComponent(id_pelanggan, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCariPelanggan)
                            .addComponent(btnUploadImage))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(id_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCariPelanggan, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(17, 17, 17)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(nama_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(no_telp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(foto_desain, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUploadImage))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(236, 50, 55));
        jLabel13.setText("Detail Transaksi");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel7.setText("Jumlah Pesanan");

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel14.setText("Jenis Baju");

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel17.setText("Warna");

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel18.setText("Total Biaya");

        warna.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        warna.setEnabled(false);

        total_biaya.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        total_biaya.setEnabled(false);

        jenis_baju.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jenis_baju.setEnabled(false);

        btnCariBarang.setBackground(new java.awt.Color(255, 255, 255));
        btnCariBarang.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btnCariBarang.setForeground(new java.awt.Color(236, 50, 55));
        btnCariBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-search-30 (1).png"))); // NOI18N
        btnCariBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariBarangActionPerformed(evt);
            }
        });

        biaya_persatuan.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        biaya_persatuan.setEnabled(false);

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel22.setText("Biaya Bahan Persatuan");

        jumlah_pesanan.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        btnHitung.setBackground(new java.awt.Color(255, 255, 255));
        btnHitung.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btnHitung.setForeground(new java.awt.Color(236, 50, 55));
        btnHitung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-calculator-30.png"))); // NOI18N
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        btnInput.setBackground(new java.awt.Color(255, 255, 255));
        btnInput.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnInput.setForeground(new java.awt.Color(236, 50, 55));
        btnInput.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-input-30.png"))); // NOI18N
        btnInput.setText("Input");
        btnInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdate.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(236, 50, 55));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-edit-30.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(236, 50, 55));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-delete-30.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(255, 255, 255));
        btnClear.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnClear.setForeground(new java.awt.Color(236, 50, 55));
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-eraser-30.png"))); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel23.setText("Pembayaran");

        buttonGroup1.add(rbLunas);
        rbLunas.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        rbLunas.setText("Lunas");
        rbLunas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLunasActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb20);
        rb20.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        rb20.setText("DP 20%");
        rb20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb20ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb50);
        rb50.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        rb50.setText("DP 50%");
        rb50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb50ActionPerformed(evt);
            }
        });

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel24.setText("Total Bayar");

        total_bayar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        total_bayar.setEnabled(false);

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel15.setText("Id Barang");

        id_barang.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        id_barang.setEnabled(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(btnInput)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(266, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel7)
                    .addComponent(jLabel18)
                    .addComponent(jLabel14)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(total_biaya, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                        .addComponent(total_bayar)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(rbLunas)
                            .addGap(18, 18, 18)
                            .addComponent(rb20)
                            .addGap(18, 18, 18)
                            .addComponent(rb50)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(id_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCariBarang))
                    .addComponent(jenis_baju, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(warna, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(biaya_persatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jumlah_pesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(id_barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCariBarang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jenis_baju, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(warna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(biaya_persatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jumlah_pesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(total_biaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(rbLunas)
                            .addComponent(rb20)
                            .addComponent(rb50))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(total_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnInput)
                            .addComponent(btnUpdate)
                            .addComponent(btnDelete)
                            .addComponent(btnClear)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public Connection setKoneksi(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/kickerz","root","");
            stm=conn.createStatement();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,"Koneksi Gagal :" +e);
        }
       return conn; 
    }
    
    public void tabel_penjualan(){
        Object header[]={"Id Transaksi","Tgl Transaksi","Id_Pelanggan","Nama Pelanggan","Alamat","No. Telepon","Id Barang","Jenis Baju","Warna","Biaya /Pcs","Jumlah Pesanan","Total Biaya","Pembayaran","Total Bayar","SRC DESAIN"};
        DefaultTableModel data=new DefaultTableModel(null,header);
        tabel_penjualan.setModel(data);
        setKoneksi();
        String sql="SELECT * FROM data_penjualan";
        try {
            ResultSet rs=stm.executeQuery(sql);
            while (rs.next())
            {
                String kolom1=rs.getString("id_transaksi");
                String kolom2=rs.getString("tgl_transaksi");
                String kolom3=rs.getString("id_pelanggan");
                String kolom4=rs.getString("nama_pelanggan");
                String kolom5=rs.getString("alamat");
                String kolom6=rs.getString("no_telp");
                String kolom7=rs.getString("id_barang");
                String kolom8=rs.getString("jenis_baju");
                String kolom9=rs.getString("warna");
                String kolom10=rs.getString("biaya_persatuan");
                String kolom11=rs.getString("jumlah_pesanan");
                String kolom12=rs.getString("total_biaya");
                String kolom13=rs.getString("pembayaran");
                String kolom14=rs.getString("total_bayar");
                String kolom15=rs.getString("foto_desain");
                
                String kolom[]={kolom1,kolom2,kolom3,kolom4,kolom5,kolom6,kolom7,kolom8,kolom9,kolom10,kolom11,kolom12,kolom13,kolom14,kolom15};
                data.addRow(kolom);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Data Gagal Dipanggil"+e);
        }
    }
    
    public void Tampil_ID(){
        try {
            ResultSet rs = stm.executeQuery("SELECT * FROM data_penjualan ORDER BY id_transaksi DESC");

            if (rs.next()) {
                int lastID = Integer.parseInt(rs.getString("id_transaksi").substring(5));
                int newID = lastID + 1;
                String AN = String.format("%05d", newID);
                id_transaksi.setText("PNJLN" + AN);
            } else {
                id_transaksi.setText("PNJLN00001");
            }
        } catch (Exception e) {
            id_transaksi.setText("PNJLN00001");
        }
    }
    private void id_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_transaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_transaksiActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        kosong();
        tabel_penjualan();
    }//GEN-LAST:event_btnClearActionPerformed

    private void rbLunasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLunasActionPerformed
        // TODO add your handling code here:
        int harga = Integer.parseInt(total_biaya.getText());
        int bayar = 0;
        
        if(rbLunas.isSelected()){
            bayar = (int) (harga *1);
        }
        total_bayar.setText(""+bayar);
    }//GEN-LAST:event_rbLunasActionPerformed

    private void rb20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb20ActionPerformed
        // TODO add your handling code here:
        int harga = Integer.parseInt(total_biaya.getText());
        int bayar = 0;
        
        if(rb20.isSelected()){
            bayar = (int) (harga *0.2);
        }
        total_bayar.setText(""+bayar);
    }//GEN-LAST:event_rb20ActionPerformed

    private void rb50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb50ActionPerformed
        // TODO add your handling code here:
        int harga = Integer.parseInt(total_biaya.getText());
        int bayar = 0;
        
        if(rb50.isSelected()){
            bayar = (int) (harga *0.5);
        }
        total_bayar.setText(""+bayar);
    }//GEN-LAST:event_rb50ActionPerformed

    private void btnInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputActionPerformed
        // TODO add your handling code here:
        String method = null;
        if(rbLunas.isSelected()) {
            method = "Lunas";
        } else if(rb20.isSelected()) {
            method = "DP 20%";
        } else if(rb50.isSelected()) {
            method = "DP 50%";
        }

        SimpleDateFormat fm = new SimpleDateFormat("yyyy-MM-dd");   
        String tgl = String.valueOf(fm.format(tgl_transaksi.getDate()));

        String sql = "insert into data_penjualan values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
        // INPUT DATA PENJUALAN
        try {         
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, id_transaksi.getText());
            stat.setString(2, tgl);
            stat.setString(3, id_pelanggan.getText());
            stat.setString(4, nama_pelanggan.getText());
            stat.setString(5, alamat.getText());
            stat.setString(6, no_telp.getText());
            stat.setString(7, id_barang.getText());
            stat.setString(8, jenis_baju.getText());
            stat.setString(9, warna.getText());
            stat.setString(10, biaya_persatuan.getText());
            stat.setString(11, jumlah_pesanan.getText());
            stat.setString(12, total_biaya.getText());
            stat.setString(13, method);
            stat.setString(14, total_bayar.getText());
            InputStream IS = new FileInputStream(new File(path2));
            stat.setBlob(15, IS);

            stat.execute();
            

            // Update stock barang
            String updateStockQuery = "UPDATE data_barang SET stock = stock - ? WHERE id_barang = ?";
            PreparedStatement updateStockStat = conn.prepareStatement(updateStockQuery);
            updateStockStat.setInt(1, Integer.parseInt(jumlah_pesanan.getText()));
            updateStockStat.setString(2, id_barang.getText());
            updateStockStat.executeUpdate();

            JOptionPane.showMessageDialog(null, "Data akan disimpan dan stok barang diperbarui");
            kosong();
            id_transaksi.requestFocus();
            tabel_penjualan();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Data gagal disimpan. Error: " + e.getMessage());
            tabel_penjualan();
        }
    }//GEN-LAST:event_btnInputActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
        int biaya = Integer.parseInt(biaya_persatuan.getText());
        int pesanan = Integer.parseInt(jumlah_pesanan.getText());
        int total = 0;
        
        total = (int) (biaya*pesanan);
        total_biaya.setText(""+total);
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String method = null;
        if (rbLunas.isSelected()) {
            method = "Lunas";
        } else if (rb20.isSelected()) {
            method = "DP 20%";
        } else if (rb50.isSelected()) {
            method = "DP 50%";
        }

        SimpleDateFormat fm = new SimpleDateFormat("yyyy-MM-dd");
        String tgl = String.valueOf(fm.format(tgl_transaksi.getDate()));

        try {
            String sql = "UPDATE data_penjualan SET "
                    + "id_transaksi=?,"
                    + "tgl_transaksi=?,"
                    + "id_pelanggan=?,"
                    + "nama_pelanggan=?,"
                    + "alamat=?,"
                    + "no_telp=?,"
                    + "id_barang=?,"
                    + "jenis_baju=?,"
                    + "warna=?,"
                    + "biaya_persatuan=?,"
                    + "jumlah_pesanan=?,"
                    + "total_biaya=?,"
                    + "pembayaran=?,"
                    + "total_bayar=?,"
                    + "foto_desain=? "
                    + "WHERE id_transaksi=?";
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, id_transaksi.getText());
            stat.setString(2, tgl);
            stat.setString(3, id_pelanggan.getText());
            stat.setString(4, nama_pelanggan.getText());
            stat.setString(5, alamat.getText());
            stat.setString(6, no_telp.getText());
            stat.setString(7, id_barang.getText());
            stat.setString(8, jenis_baju.getText());
            stat.setString(9, warna.getText());
            stat.setString(10, biaya_persatuan.getText());
            stat.setString(11, jumlah_pesanan.getText());
            stat.setString(12, total_biaya.getText());
            stat.setString(13, method);
            stat.setString(14, total_bayar.getText());
            InputStream IS = new FileInputStream(new File(path2));
            stat.setBlob(15, IS);
            stat.setString(16, id_transaksi.getText());

            int affectedRows = stat.executeUpdate();
            if (affectedRows > 0) {
                JOptionPane.showMessageDialog(rootPane, "Data Telah Diubah");
                kosong();
                id_transaksi.requestFocus();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Tidak ada data yang diubah.");
            }
            tabel_penjualan();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Data Gagal Diubah: " + e.getMessage());
        }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(rootPane,"Hapus Data Ini ?","Konfirmasi",JOptionPane.YES_NO_OPTION);
         if (ok==0){
             String sql = "DELETE from data_penjualan where id_transaksi ='"+id_transaksi.getText()+"'";
             try{
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "Data Akan Dihapus Dari Sistem ?");
                kosong();
                id_transaksi.requestFocus();
             }
                catch (SQLException e){
                JOptionPane.showMessageDialog(rootPane, "Data Gagal Dihapus"+e);
             }
         tabel_penjualan();
         }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCariPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariPenjualanActionPerformed
        // TODO add your handling code here:
        Object header[]={"Id Transaksi","Tgl Transaksi","Id_Pelanggan","Nama Pelanggan","Alamat","No. Telepon","Id Barang","Jenis Baju","Warna","Biaya /Pcs","Jumlah Pesanan","Total Biaya","Pembayaran","Total Bayar"};
        DefaultTableModel data=new DefaultTableModel(null,header);
        tabel_penjualan.setModel(data);
       
        setKoneksi();
        String sql="SELECT * FROM data_penjualan WHERE id_transaksi like '%" + cariData.getText() + "%'" 
                +"or nama_pelanggan like '%" + cariData.getText()+"%'";
       
          try {
            ResultSet rs=stm.executeQuery(sql);
            while (rs.next())
            {
                String kolom1=rs.getString("id_transaksi");
                String kolom2=rs.getString("tgl_transaksi");
                String kolom3=rs.getString("id_pelanggan");
                String kolom4=rs.getString("nama_pelanggan");
                String kolom5=rs.getString("alamat");
                String kolom6=rs.getString("no_telp");
                String kolom7=rs.getString("id_barang");
                String kolom8=rs.getString("jenis_baju");
                String kolom9=rs.getString("warna");
                String kolom10=rs.getString("biaya_persatuan");
                String kolom11=rs.getString("jumlah_pesanan");
                String kolom12=rs.getString("total_biaya");
                String kolom13=rs.getString("pembayaran");
                String kolom14=rs.getString("total_bayar");
                
                String kolom[]={kolom1,kolom2,kolom3,kolom4,kolom5,kolom6,kolom7,kolom8,kolom9,kolom10,kolom11,kolom12,kolom13,kolom14};
                data.addRow(kolom);
            }
            kosong();

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnCariPenjualanActionPerformed

    private void tabel_penjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_penjualanMouseClicked
        // TODO add your handling code here:
        SimpleDateFormat SDF = new SimpleDateFormat("yyyy-MM-dd");
        Date Tgl = null;
        
        int r = tabel_penjualan.getSelectedRow();
        String click = (tabel_penjualan.getModel().getValueAt(r, 0).toString());
        String sql = "SELECT * FROM data_penjualan WHERE id_transaksi = '" +click+ "'";
        
        try{
            PreparedStatement ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();
            if (rs.next()){
                String id_trans = rs.getString(1);
                Tgl = rs.getDate(2);
                String id_pplgn = rs.getString(3);
                String nama = rs.getString(4);
                String alamat_pelanggan = rs.getString(5);
                String no_telepon = rs.getString(6);
                String id_brng = rs.getString(7);
                String jenis = rs.getString(8);
                String warna_baju = rs.getString(9);
                String biaya_perpcs = rs.getString(10);
                String jmlh = rs.getString(11);
                String total_b = rs.getString(12);
                String method = rs.getString(13);
                String bayar = rs.getString(14);
                Blob image = rs.getBlob(15);
                
                String path = "D:\\NetbeansProject\\The_Kickerz\\src\\upload\\img.jpg";
                path2 = path;
                byte[] bytea = image.getBytes(1, (int) image.length());
                FileOutputStream fos = new FileOutputStream(path2);
                fos.write(bytea);

                // Buat ImageIcon
                ImageIcon icon = new ImageIcon(bytea);
                Image img = icon.getImage().getScaledInstance(foto_desain.getWidth(), foto_desain.getHeight(), Image.SCALE_SMOOTH);

                
                id_transaksi.setText(id_trans);
                tgl_transaksi.setDate(Tgl);
                id_pelanggan.setText(id_pplgn);
                nama_pelanggan.setText(nama);
                alamat.setText(alamat_pelanggan);
                no_telp.setText(no_telepon);
                id_barang.setText(id_brng);
                jenis_baju.setText(jenis);
                warna.setText(warna_baju);
                biaya_persatuan.setText(biaya_perpcs);
                jumlah_pesanan.setText(jmlh);
                total_biaya.setText(total_b);
                total_bayar.setText(bayar);
                foto_desain.setIcon(new ImageIcon(img));
                // Mengatur radio button berdasarkan nilai pembayaran
                if (method.equals("Lunas")) {
                    rbLunas.setSelected(true);
                } else if (method.equals("DP 20%")) {
                    rb20.setSelected(true);
                } else if (method.equals("DP 50%")) {
                    rb50.setSelected(true);
                }
            }
        } catch(Exception e){
            
        }
    }//GEN-LAST:event_tabel_penjualanMouseClicked

    private void btnCariPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariPelangganActionPerformed
        // TODO add your handling code here:
        menuPelanggan MP = new menuPelanggan(this);
        jDesktopPane1.add(MP);
        this.getParent().add(MP);
        MP.setVisible(true);
    }//GEN-LAST:event_btnCariPelangganActionPerformed

    private void btnCariBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariBarangActionPerformed
        // TODO add your handling code here:
        menuBarang MB = new menuBarang(this);
        jDesktopPane1.add(MB);
        this.getParent().add(MB);
        MB.setVisible(true);
    }//GEN-LAST:event_btnCariBarangActionPerformed

    private void btnUploadImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadImageActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File F = chooser.getSelectedFile();
        String path = F.getAbsolutePath();
        try{
            BufferedImage BI = ImageIO.read(new File(path));    
            Image img = BI.getScaledInstance(foto_desain.getWidth(),foto_desain.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(img);
            foto_desain.setIcon(icon);
            path2 = path;
        }catch(IOException e) {
            JOptionPane.showMessageDialog(null, "ERROR UPLOAD GAMBAR" +e);
        }
    }//GEN-LAST:event_btnUploadImageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea alamat;
    public javax.swing.JTextField biaya_persatuan;
    private javax.swing.JButton btnCariBarang;
    private javax.swing.JButton btnCariPelanggan;
    private javax.swing.JButton btnCariPenjualan;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnInput;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUploadImage;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cariData;
    private javax.swing.JLabel foto_desain;
    public javax.swing.JTextField id_barang;
    public javax.swing.JTextField id_pelanggan;
    private javax.swing.JTextField id_transaksi;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextField jenis_baju;
    private javax.swing.JTextField jumlah_pesanan;
    public javax.swing.JTextField nama_pelanggan;
    public javax.swing.JTextField no_telp;
    private javax.swing.JRadioButton rb20;
    private javax.swing.JRadioButton rb50;
    private javax.swing.JRadioButton rbLunas;
    private javax.swing.JTable tabel_penjualan;
    private com.toedter.calendar.JDateChooser tgl_transaksi;
    private javax.swing.JTextField total_bayar;
    private javax.swing.JTextField total_biaya;
    public javax.swing.JTextField warna;
    // End of variables declaration//GEN-END:variables
}
